### ISSUE TITLE
getContentTemplate function does not recognize mediatype parameter

### ISSUE THREAD

**Issue by edcolon** [donbalon4/API_Alfresco#1]
Hi, 

when passing parameter mediatype to upload documents with the original code there's a problem that leaves spaces in the "media type" string for example "                    application/pdf                 ". This prevents to see preview document inside Alfresco 5.1.

To avoid this problem, we fixed by rewriting code in one line like this in file cmis_service.php (around line 742):
cmisra:mediatype{content_type}/cmisra:mediatype 

That works for us!

**Comment by donbalon4** [comment]
Hi Ed!
Thanks for share your solution!

**Comment by miquelp** [comment]
Hi @edcolon, I'm having that exact same issue in Alfresco 5.1, could you be a bit more specific about how did you solve it? @donbalon4  Is this fix already on repository's code? My Alfresco installation can't seem to get mime types from files (I just see "Mime Type: Unknown"), so I can't see any templates or preview files within Alfresco. It works when I upload a file in any other way, so I guess this issue is coming from library.

**Comment by mql21** [comment]
Hi @edcolon, I had the same issue and I could fix it through the way you mention. Thanks!

P.S: There's a problem in your original message and the "<>" symbols don't appear so it can lead to confusion. It took me a few minutes to figure out that it was indeed:

` <cmisra:mediatype>{content_type}</cmisra:mediatype>`

Anyway thanks for pointing out the issue!

**Comment by mql21** [comment]
I've started a pull request to fix this issue following @edcolon way. I've tested it (also have Alfresco 5.1) and it does the trick.

Thanks!
